export const KAOMOJIS = [
  "(^_^)",
  "(￣▽￣)/",
  "(╯°□°）╯︵ ┻━┻",
  "(¬‿¬)",
  "(づ｡◕‿‿◕｡)づ",
  "ヽ(＾Д＾)ﾉ",
  "（￣へ￣）",
  "（╯°□°）╯︵ ┻━┻",
  "（＾ω＾）",
  "(✿◠‿◠)",
  "(｡♥‿♥｡)",
  "(╯°□°）╯︵ ┻━┻",
  "(❁´◡`❁)",
  "╰(*°▽°*)╯",
  "ᓚᘏᗢ",
  "٩(◕‿◕)۶",
  "(◡‿◡✿)",
  "ლ(╹◡╹ლ)",
  "(｡◕‿◕｡)",
  "(*^ω^*)",
  "ヽ(o^▽^o)/",
  "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧",
  "(*˘︶˘*).｡*♡",
  "(´∀｀♡)",
  "\\(^o^)/",
  "(≧◡≦)",
  "♡(˃͈ દ ˂͈ ༶ )",
  "( ˶ᵔ ᵕ ᵔ˶ )",
  "ฅ^•ﻌ•^ฅ",
  "(ﾉ´ヮ`)ﾉ*: ･ﾟ",
  "૮₍˶ᵔ ᵕ ᵔ˶₎ა",
  "( ˘ ³˘)♥",
  "✧⁺⸜(●˙▾˙●)⸝⁺✧",
  "ʚ♡⃛ɞ(ू•ᴗ•ू❁)",
  "(｡◝‿◜｡)",
  "⸜(｡˃ ᵕ < )⸝♡",
];
// Word list for readable passwords (3-14 characters)
// Organized by length for efficient selection
export const WORD_LIST = {
  3: [
    "cat",
    "dog",
    "sun",
    "car",
    "bus",
    "pen",
    "cup",
    "hat",
    "key",
    "map",
    "box",
    "egg",
    "ice",
    "jar",
    "net",
    "owl",
    "pig",
    "rat",
    "tea",
    "joy",
    "red",
    "hot",
    "big",
    "new",
    "old",
    "top",
    "run",
    "fly",
    "sky",
    "day",
    "fun",
    "web",
    "zip",
    "lol",
    "wow",
    "yes",
    "not",
  ],

  4: [
    "moon",
    "star",
    "tree",
    "bird",
    "fish",
    "book",
    "door",
    "fire",
    "wind",
    "rain",
    "snow",
    "blue",
    "love",
    "hope",
    "play",
    "calm",
    "dare",
    "ease",
    "fine",
    "glow",
    "hunt",
    "idea",
    "jazz",
    "keen",
    "luxe",
    "muse",
    "nova",
    "opal",
    "pure",
    "quip",
    "rise",
    "soar",
    "true",
    "urge",
    "vast",
    "wisp",
    "yarn",
    "zest",
    "bold",
    "care",
    "fair",
    "gift",
    "hero",
    "king",
    "luck",
    "mind",
    "open",
    "soft",
    "wave",
    "kdsm"
  ],

  5: [
    "peace",
    "light",
    "magic",
    "dream",
    "wish",
    "dance",
    "smile",
    "happy",
    "brave",
    "smart",
    "quick",
    "swift",
    "apple",
    "bread",
    "chair",
    "earth",
    "flame",
    "green",
    "house",
    "kite",
    "music",
    "night",
    "ocean",
    "panda",
    "queen",
    "river",
    "tiger",
    "unity",
    "water",
    "zebra",
    "beach",
    "cloud",
    "daisy",
    "eagle",
    "frost",
    "heart",
    "lotus",
    "mango",
    "ninja",
    "orbit",
    "pearl",
    "tulip",
    "ultra",
    "viper",
    "xenon",
    "great",
    "royal",
    "stone",
    "bloom",
    "charm",
    "idris"
  ],

  6: [
    "island",
    "jungle",
    "valley",
    "golden",
    "silver",
    "mighty",
    "sakina",
    "butter",
    "gentle",
    "spirit",
    "shadow",
    "bright",
    "mystic",
    "cipher",
    "dragon",
    "falcon",
    "garden",
    "harbor",
    "jewels",
    "knight",
    "lantern",
    "marble",
    "nature",
    "oxygen",
    "palace",
    "quartz",
    "raptor",
    "saddle",
    "temple",
    "unique",
    "violin",
    "walrus",
    "wonder",
    "yellow",
    "zenith",
    "arctic",
    "bridge",
    "castle",
    "desert",
    "empire",
    "forest",
    "galaxy",
    "heaven",
    "iconic",
  ],

  7: [
    "freedom",
    "courage",
    "victory",
    "journey",
    "harmony",
    "mystery",
    "respect",
    "justice",
    "balance",
    "thunder",
    "rainbow",
    "crystal",
    "diamond",
    "emerald",
    "phoenix",
    "unicorn",
    "warrior",
    "kingdom",
    "triumph",
    "pioneer",
    "fortune",
    "destiny",
    "cascade",
    "glacier",
    "sunrise",
    "moonlit",
    "starlit",
    "radiant",
    "crystal",
    "legends",
    "supreme",
    "perfect",
    "amazing",
    "awesome",
    "dynamic",
    "eternal",
    "forever",
  ],

  8: [
    "treasure",
    "serenity",
    "strength",
    "majestic",
    "champion",
    "brilliant",
    "infinite",
    "paradise",
    "creation",
    "guardian",
    "horizons",
    "luminous",
    "sentinel",
    "conquest",
    "endeavor",
    "flourish",
    "graceful",
    "heritage",
    "imperial",
    "jubilant",
    "kindness",
    "magnitude",
    "nobility",
    "overflow",
    "pristine",
    "equality",
    "radiance",
    "sapphire",
    "titanium",
    "universe",
    "valiance",
    "wellness",
    "yearning",
    "glorious",
  ],

  9: [
    "adventure",
    "beautiful",
    "wonderful",
    "challenge",
    "discovery",
    "excellent",
    "fearless",
    "greatness",
    "happiness",
    "integrity",
    "knowledge",
    "legendary",
    "marvelous",
    "navigator",
    "outstanding",
    "potential",
    "qualities",
    "resolute",
    "sovereign",
    "transform",
    "unstoppable",
    "vibrance",
    "wholesome",
    "youthful",
    "celestial",
    "dedicated",
    "elevation",
    "fantastic",
    "gratitude",
    "harmonize",
  ],

  10: [
    "accomplish",
    "breathtaking",
    "confidence",
    "dedication",
    "enthusiasm",
    "generation",
    "illuminate",
    "jubilation",
    "leadership",
    "magnificence",
    "passionate",
    "prosperity",
    "revolution",
    "spectacular",
    "transcend",
    "victorious",
    "wavelength",
    "excellence",
    "foundation",
    "historical",
    "imaginative",
    "joyfulness",
    "kindheartedness",
    "motivation",
    "persistent",
    "remarkable",
  ],

  11: [
    "achievement",
    "cooperation",
    "development",
    "encouraging",
    "fundamental",
    "generosity",
    "intelligent",
    "magnificent",
    "outstanding",
    "performance",
    "qualitative",
    "respectable",
    "trustworthy",
    "wonderfully",
    "celebration",
    "enlightening",
    "flexibility",
    "imagination",
    "joyfulness",
    "magnificent",
    "personality",
    "remarkable",
  ],

  12: [
    "acceleration",
    "breakthrough",
    "contribution",
    "determination",
    "experiencing",
    "independence",
    "inspirational",
    "professional",
    "relationship",
    "significance",
    "transformation",
    "acknowledged",
    "appreciation",
    "capabilities",
    "conservation",
    "furthermore",
    "heartwarming",
    "illumination",
    "masterpiece",
  ],

  13: [
    "collaboration",
    "determination",
    "extraordinary",
    "implementation",
    "understanding",
    "comprehensive",
    "encouragement",
    "philosophical",
    "revolutionary",
    "transparency",
    "accomplishment",
    "consideration",
    "effectiveness",
    "fortification",
    "harmonization",
  ],

  14: [
    "accountability",
    "characteristics",
    "congratulations",
    "recommendation",
    "responsibility",
    "transformation",
    "administration",
    "differentiation",
    "infrastructure",
    "representation",
    "authentication",
    "consciousness",
    "implementation",
    "interpretation",
  ],
};

// Helper function to get words by length
export const getWordsByLength = (length) => WORD_LIST[length] || [];

// Get all words as flat array (for backward compatibility)
export const getAllWords = () => {
  const allWords = [];
  for (const length in WORD_LIST) {
    allWords.push(...WORD_LIST[length]);
  }
  return allWords;
};
export const FAQs = [
  {
    question: "Can I recover my message if I lose the key?",
    answer:
      "No. Without the exact key used for encryption, it's not possible to decrypt the message. There is no recovery mechanism by design for security reasons.",
  },
  {
    question: "What is the maximum length for custom keys?",
    answer:
      "The maximum length for custom keys is 200 characters. Keys longer than this will be truncated or rejected to ensure optimal performance and security.",
  },
  {
    question: "What is the maximum length for messages?",
    answer:
      "According to tests conducted the maximum length for messages is just above 100k but, 20k characters for messages is considered to be optimal. Messages longer than this will be truncated or rejected to ensure optimal performance and security.",
  },
  {
    question: "How do I get an API key?",
    answer:
      "Sign up for an account, navigate to your Profile page, click on the Developer tab, and create a new API key. You can create up to 3 API keys per account.",
  },
  {
    question: "What happens if I exceed the rate limit?",
    answer:
      "If you exceed your daily API call limit (10 for free users, 100 for premium), you'll receive a 429 error response. Rate limits reset daily at midnight UTC.",
  },
  {
    question: "Can I use the API for commercial projects?",
    answer:
      "Yes, you can use the KDSM API for both personal and commercial projects. However, please respect the rate limits and terms of service.",
  },
  {
    question: "Is KDSM encryption secure?",
    answer:
      "KDSM provides solid security for everyday communication needs. The encryption strength depends on key secrecy and proper implementation.",
  },
  {
    question: "What's the difference between API keys and encryption keys?",
    answer:
      "API keys authenticate your access to the KDSM service, while encryption keys are used to encrypt/decrypt your actual messages. Both are required but serve different purposes.",
  },
  {
    question: "Is KDSM Open Source?",
    answer:
      "No, KDSM Encryptor is not an open-source project. The KDSM algorithm is proprietary and maintained by a select team to ensure security and integrity.",
  },
  {
    question: "Can I delete my API keys?",
    answer:
      "Yes, you can delete API keys from your profile > developer tab. Once deleted, they are immediately revoked and cannot be restored. Make sure to update any applications using the deleted key.",
  },
];

export const socialIcons = [
  "facebook",
  "x",
  "spotify",
  "stackoverflow",
  "linkedin",
  "instagram",
  "upwork",
  "github",
  "youtube",
  "pinterest",
  "reddit",
  "tumblr",
  "snapchat",
  "tiktok",
  "whatsapp",
  "discord",
  "slack",
  "telegram",
  "medium",
  "dribbble",
  "behance",
  "flickr",
  "vk",
  "onlyfans",
]